---
layout: cv
title: Lincoln Tady's CV
---
# Lincoln Tady
Business Analytics Student

## Education

### Brigham Young University-Idaho
__GPA : 3.54__
__Scholarship: Thomas E Ricks Scholarship__
__Certificate: Business Administration__

## Experience

### Kimberly-Clark
#### Innovation Data Analytics and Insights Intern
__Filtered and compiled data cases to find $2.5 million in Working Capital Saved__
__Created and updated multiple Power BI dashboards that reached out to the organization’s higher-ups__
__Analyzed, compiled, and presented multiple projects to different teams in order to assist in decision-making__
__Assisted in the running of a GBS-wide hackathon that resulted in $70 million in potential savings for the following year__

### Brigham Young University-Idaho
#### Data Visualization Specialist
__Generated multiple reports in Power BI that sped up the degree verification process by 25%__
__Built a dashboard in Power BI to show the most pressing daily tasks which increased productivity by 20%__
__Communicated with shareholders to create necessary reports and dashboards__
__Presented 3 of my reports to the University President and his Council__

#### Degree Verification Lead Processor
__Created an automated Outlook response to send to students which reduced monthly interactions by 35%__
__Utilized Excel to create a workbook to store necessary graduation data stopping a data loss issue__
__Interviewed over 40 candidates for positions in the organization__
__Directed a group of 5 workers in day-to-day tasks__

#### Degree Verification Processor
__Utilized Excel to fully automate a process that initially took 6 hours__
__Maintained a 99% overall accuracy in degree processing__
__Developed customer service skills by answering between 50 and 100 emails and phone calls daily__
__Handled sensitive information with care__


## Additional Information
__Hard Skills: Advanced Excel, Power BI, Tableau, SQL, R-Studio, Python__
__Soft Skills: Problem Solver, Effective Communicator, Natural Leader, Active Listener, Critical Thinker__
__Languages: Spanish- Fluent__



<!-- ### Footer

Last updated: April 2025 -->